spring:
  application:
    name: oauth2-client

server:
  port: 8081


# OAuth2 ????????

oauth2.client.id: client123
# ??: ???????????????????client_id??
# ???: ??????????????

oauth2.client.secret: secret456
# ??: ?????????????????????
# ???: ????????????????????

oauth2.authorization.uri: http://localhost:8080/oauth/authorize
# ??: ????URL??????????URL???????
# ??: OAuth2???Authorization Endpoint

oauth2.token.uri: http://localhost:8080/oauth/token
# ??: ????URL???????????????API??
# ??: OAuth2???Token Endpoint

oauth2.userinfo.uri: http://localhost:8080/oauth/userinfo
# ??: ??????URL???????????????
# ??: OpenID Connect?UserInfo Endpoint

oauth2.redirect.uri: http://localhost:8081/callback
# ??: ???URI?????????????????????
# ???: ???????????redirect_uri????

