spring:
  application:
    name: oauth2-client

server:
  port: 8081


# OAuth2 ????????

oauth2.client.id: client123


oauth2.client.secret: secret456


oauth2.authorization.uri: http://localhost:8080/oauth/authorize


oauth2.token.uri: http://localhost:8080/oauth/token


oauth2.userinfo.uri: http://localhost:8080/oauth/userinfo


oauth2.redirect.uri: http://localhost:8081/callback


